def draw_school():
    print(" -------------------- ")
    print("|      BU SCHOOL     |")
    print("|    _          _    |")
    print("|   |_|        |_|   |")
    print("|    _          _    |")
    print("|   |_|        |_|   |")
    print("|    _          _    |")
    print("|   |_|        |_|   |")
    print("|    _          _    |")
    print("|   |_|        |_|   |")
    print("|    _          _    |")
    print("|   |_|        |_|   |")
    print("|       ______       |")
    print("|      |      |      |")
    print("|      |      |      |")
    print("|      |      |      |")
    print("|      |      |      |")
    print(" -------------------- ")

draw_school()